name: Telegram Notifications

on:
  workflow_call:
    secrets:
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_TOKEN:
        required: true
      MESSAGE_THREAD_ID:
        required: true
  issues:
  push:
  pull_request:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  release:
    types: [ published ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        id: vars
        run: echo ::set-output name=branch_name::${GITHUB_REF##*/}

      - name: Send Issues notifications to Telegram
        if: github.event_name == 'issues'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="MarkdownV2" >> /dev/null
        env:
          MESSAGE: |
            🤖 The Issue [ ${{ github.event.issue.title }} ] 
            was ${{ github.event.action }} 
            by ${{ github.actor }}: 
            
            ASSIGNEE(S): ${{github.event.issue.assignees[0].login}} ${{github.event.issue.assignees[1].login}} ${{github.event.issue.assignees[2].login}} ${{github.event.issue.assignees[3].login}} ${{github.event.issue.assignees[4].login}}

            View issue: ${{ github.event.issue.html_url }}

      - name: Escape commit message
        if: github.event_name == 'push'
        id: escape_commit
        run: |
          COMMIT_MESSAGE="${{ github.event.commits[0].message }}"
          COMMIT_MESSAGE="$(echo "${COMMIT_MESSAGE}" | xargs)"
          ESCAPED_MESSAGE="${COMMIT_MESSAGE//_/\\_}"
          ESCAPED_MESSAGE="${ESCAPED_MESSAGE//\*/}"
          echo "escaped_message=${ESCAPED_MESSAGE}" >> $GITHUB_OUTPUT

      - name: Send Push notifications to Telegram
        if: github.event_name == 'push'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="Markdown" >> /dev/null
        env:
          MESSAGE: |
            ✅ *Push commit into ${{ steps.vars.outputs.branch_name }}*
            👉 ${{ github.repository }} by ${{ github.actor }}. 

            ${{ steps.escape_commit.outputs.escaped_message }}

            View changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            ---------------------------------

      - name: Escape PR title
        if: github.event_name == 'pull_request'
        id: escape_title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          ESCAPED_TITLE="${PR_TITLE//_/\\_}"
          echo "escaped_title=${ESCAPED_TITLE}" >> $GITHUB_OUTPUT

      - name: Send PR notifications to Telegram
        if: github.event_name == 'pull_request'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="Markdown" >> /dev/null
        env:
          MESSAGE: |
            🔥 *Pull Request ${{ github.event.action }}*
            👉 ${{ github.repository }} by ${{ github.actor }}. 

            ${{ steps.escape_title.outputs.escaped_title }}

            View PR: ${{ github.event.pull_request.html_url }}

            ---------------------------------

      - name: Send Issue Comment notifications to Telegram
        if: github.event_name == 'issue_comment'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="Markdown" >> /dev/null
        env:
          MESSAGE: |
            🤖 ${{ github.event_name }} ${{ github.event.action }} 
            in ${{ github.repository }} by ${{ github.actor }}. 

            Branch: ${{ steps.vars.outputs.branch_name }}

            View issue: ${{ github.event.issue.html_url }}

      - name: Send PR Review Comment notifications to Telegram
        if: github.event_name == 'pull_request_review'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="Markdown" >> /dev/null
        env:
          MESSAGE: |
            🤖 ${{ github.event_name }} ${{ github.event.action }} 
            in ${{ github.repository }} by ${{ github.actor }}. 

            Branch: ${{ steps.vars.outputs.branch_name }}

            View pull request: ${{ github.event.pull_request.html_url }}

            ---------------------------------

      - name: Escape release body
        if: github.event_name == 'release'
        id: escape_release
        run: |
          RELEASE_BODY="${{ github.event.release.body }}"
          ESCAPED_BODY="${RELEASE_BODY//_/\\_}"
          echo "escaped_body<<EOF" >> $GITHUB_OUTPUT
          echo "${ESCAPED_BODY}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Release notifications to Telegram
        if: github.event_name == 'release'
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" -d message_thread_id=${{ secrets.MESSAGE_THREAD_ID }} -d parse_mode="Markdown" >> /dev/null
        env:
          MESSAGE: |
            🚀 *New Release Published:* ${{ github.event.release.name }}
            📦 Tag: ${{ github.event.release.tag_name }}
            By: ${{ github.actor }}
            
            ${{ steps.escape_release.outputs.escaped_body }}
            
            👉 View Release ${{ github.event.release.html_url }}
