name: Telegram Notifications

on:
  issues:
    types: [opened, reopened, deleted, closed]
  push:
  pull_request:
    types: [assigned, opened, closed, reopened, edited, review_requested, review_request_removed, ready_for_review]
  issue_comment:
  pull_request_review:
  pull_request_review_comment:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Issues notifications to Telegram
      if: github.event_name == 'issues'
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: | 
          The Issue [ ${{ github.event.issue.title }} ] 
          was ${{ github.event.action }} 
          by ${{ github.actor }}: 
          ${{ github.event.issue.html_url }}
      
    - name: Send Push notifications to Telegram
      if: github.event_name == 'push'
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: |
          ${{ github.event_name }} commit in 
          ${{ github.repository }} by ${{ github.actor }}. 
          [${{github.sha}}@${{ github.ref }}]
  
    - name: Send PR notifications to Telegram
      if: github.event_name == 'pull_request'
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: |
          ${{ github.event_name }} ${{ github.event.action }} 
          in ${{ github.repository }} by ${{ github.actor }}. 
          [${{github.sha}}@${{ github.ref }}]
    
    - name: Send Issue Comment notifications to Telegram
      if: github.event_name == 'issue_comment' 
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: | 
          ${{ github.event_name }} ${{ github.event.action }} 
          in ${{ github.repository }} by ${{ github.actor }}. 
          [${{github.sha}}@${{ github.ref }}]
          ${{ github.event.issue.html_url }}
          
    - name: Send PR Review Comment notifications to Telegram
      if: github.event_name == 'pull_request_review' 
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: | 
          ${{ github.event_name }} ${{ github.event.action }} 
          in ${{ github.repository }} by ${{ github.actor }}. 
          [${{github.sha}}@${{ github.ref }}]
          ${{ github.event.issue.comments_url }}
          
    - name: Send PR Review Comment notifications to Telegram
      if: github.event_name == 'pull_request_review_comment'
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content
        MESSAGE: | 
          ${{ github.event_name }} ${{ github.event.action }} 
          in ${{ github.repository }} by ${{ github.actor }}. 
          [${{github.sha}}@${{ github.ref }}]
          ${{ github.event.issue.comments_url }}
          
    
      

