name: Telegram Notifications

on:
  issues:
    types: [opened, reopened, deleted, closed]
  push:
  pull_request:
  issue_comment:
  pull_request_review_comment:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send notifications to Telegram
    
      if: ${{ github.event_name }} == 'issues'
      run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="${MESSAGE}" >> /dev/null
      env:
        # Message content for issues
        MESSAGE: "The Issue [ ${{ github.event.issue.title }} ] was ${{ github.event.action }} by ${{ github.actor }}: \n${{ github.event.issue.html_url }}"
      
